sudo: required

language: generic

services:
  - docker

script:
- |
  baseDir="$(pwd)" &&\
  inputDir="${baseDir}" &&\
  outputDir="${baseDir}/pdf" &&\
  mkdir -p "${outputDir}" &&\
  docker run -v "${inputDir}/":/input/ \
             -v "${outputDir}/":/output/ \
             -e TRAVIS_COMMIT=$TRAVIS_COMMIT \
             -e TRAVIS_REPO_SLUG=$TRAVIS_REPO_SLUG \
             -t -i thomasweise/docker-bookbuilder book.md GiovannelliLab_protocols_ &&\
  cd "${outputDir}"

deploy:
  provider: pages
  skip-cleanup: true
  github-token: $GITHUB_TOKEN
  keep-history: false
  on:
    branch: master
  target-branch: master
  local-dir: output
